---

- name: Make sure Apache config directory exists
  file:
    path: /etc/apache2
    state: directory

- name: Configure Apache ports.conf file
  template:
    src: ports.conf.j2
    dest: /etc/apache2/ports.conf
  notify: reload apache2

- name: Install Apache
  apt:
    name:
      - apache2
      - libapache2-mod-auth-tkt
      - libapache2-mod-wsgi-py3
      - libapache2-mod-authz-unixgroup
      - libapache2-mod-security2
- name: Configure TKT Auth
  template:
    src: auth_tkt.conf.j2
    dest: /etc/apache2/mods-available/auth_tkt.conf
  notify: reload apache2

- name: Enable Apache modules
  shell: "a2enmod {{ item }}"
  register: apache_a2enmod
  changed_when: "'already enabled' not in apache_a2enmod.stdout"
  with_items:
    - rewrite
    - proxy
    - proxy_fcgi
    - proxy_http
    - ssl
    - auth_basic
    - auth_tkt
    - wsgi
    - remoteip
    - security2
  notify: reload apache2

- name: Configure Apache security conf
  template:
    src: security.conf.j2
    dest: /etc/apache2/conf-available/security.conf
  notify: reload apache2

- name: Configure Apache modsecurity
  template:
    src: modsecurity.conf-recommended.j2
    dest: /etc/modsecurity/modsecurity.conf-recommended
  notify: reload apache2

- name: Add module security to Apache2
  blockinfile:
    dest: /etc/apache2/apache2.conf
    block: |
      <IfModule security2_module>
        SecRuleEngine on
        ServerTokens Full
        SecServerSignature "Doesn't matter"
      </IfModule>

- name: Configure Apache remoteip conf
  template:
    src: remoteip.conf.j2
    dest: /etc/apache2/conf-available/remoteip.conf
  notify: reload apache2
